### ISSUE TITLE
Support in NativeScript

### ISSUE THREAD

**Issue by darkyelox** [material-motion/material-motion-experiments-js#243]
You think that this library would be useful in NativeScript projects? i like that idea, a simple library for my bridged projects

**Comment by appsforartists** [comment]
I'm not familiar with NativeScript, but it looks like a React Native contemporary?

Material Motion was written to be toolable and serializable (which is why our public operators are all purely declarative).  That means it could eventually be possible to write an implementation that ran on the native side of the bridge and to pass descriptions of Material Motion streams over the bridge from JS.  But, that's way farther down the line than we've scope so far.

(I don't expect you'd want to run on the JS side of a bridged environment, because I expect the cost of crossing the bridge on every frame would be terrible for performance.  However, I've never tried it.)
